version: '3'
networks:
    fiber:
services:
    fiber_app:
        build:
            context: .
        volumes:
            - ".:/go/src/fiber"
        ports:
            - "3000:3000"
            - "443:443"
        tty: true
        # If the container goes down, it will restart
        restart: "always"
        # Starts up 5 replicas of the same image
#        deploy:
#            replicas: 5
        networks:
            - fiber
    nginx:
        # specifies the latest nginx image
        image: nginx:latest
        # Connects the conf file of the container to the conf file in our folder
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./certs:/etc/nginx/certs
        # It will start up the nginx only when all api containers have started
        depends_on:
            - fiber_app
        # Connects the port 80 of the nginx container to localhost:80 or localhost
        ports:
            - "8080:8080"
        networks:
            - fiber